function [newData1] = importcsv(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 16-Nov-2020 18:25:29

% Import the file
newData1 = importdata(fileToRead1);

